apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://garfix-jaeger:16686
    isDefault: true
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
      tracesToLogs:
        datasourceUid: loki
    editable: true
