/**
 * api-types.ts — Auto-generated TypeScript types from GarfiX OpenAPI spec.
 *
 * GENERATED BY: scripts/generate-openapi-spec.ts
 * DO NOT EDIT MANUALLY — regenerate after API changes.
 *
 * These types form the SDK contract between frontend and backend.
 * Contract tests validate that the actual API responses match these types.
 */

// ═══════════════════════════════════════════════════════════════════════════════
// Domain Types
// ═══════════════════════════════════════════════════════════════════════════════

export interface ErrorResult {
  error: string;
  code?: string;
  details?: Record<string, unknown>;
}

export interface AuthResult {
  ok: boolean;
  user?: UserDTO;
  error?: string;
}

export interface UserDTO {
  id: string;
  uid: string;
  email: string;
  displayName: string;
  role: "admin" | "editor" | "employee" | "viewer";
  companies: string[];
  tokenVersion: number;
}

export interface CompanyDTO {
  id: string;
  name: string;
  nameAr?: string;
  slug: string;
  plan: "starter" | "business" | "enterprise";
  currency: "SAR" | "AED" | "KWD" | "BHD" | "QAR" | "OMR" | "EGP";
  subscriptionStatus: "active" | "trial" | "suspended" | "cancelled";
  createdAt?: string;
}

export interface InvoiceDTO {
  id: string;
  number: string;
  status: "draft" | "sent" | "paid" | "overdue" | "cancelled";
  subtotal: number;
  taxAmount: number;
  total: number;
  currency: string;
  issueDate: string;
  dueDate: string;
  clientId: string;
  lineItems: LineItemDTO[];
}

export interface LineItemDTO {
  id: string;
  productId: string;
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
  discount: number;
}

export interface VoucherDTO {
  id: string;
  number: string;
  date: string;
  description?: string;
  lines: VoucherLineDTO[];
  status: "draft" | "posted" | "reversed";
}

export interface VoucherLineDTO {
  id: string;
  accountId: string;
  debit: number;
  credit: number;
  description?: string;
}

export interface FinancialPeriodDTO {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  status: "open" | "closed" | "locked";
  companySlug: string;
}

export interface AIRequestDTO {
  input: string;
  requestType: "ocr" | "matching" | "financial_analysis" | "chat" | "whatsapp";
  companySlug: string;
  context?: Record<string, unknown>;
}

export interface AIResponseDTO {
  ok: boolean;
  resolvedBy: "cache" | "pattern" | "rule" | "memory" | "budget" | "provider_routing" | "ai";
  confidence: number;
  costUsd: number;
  latencyMs: number;
  result?: Record<string, unknown>;
}

export interface AuditLogDTO {
  id: string;
  action: string;
  actor: string;
  companySlug: string;
  details?: Record<string, unknown>;
  createdAt: string;
}

export interface WebhookEndpointDTO {
  id: string;
  url: string;
  events: string[];
  secret?: string;
  isActive: boolean;
  createdAt: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

export interface HealthCheckDTO {
  status: "healthy" | "degraded" | "down";
  version: string;
  uptime: number;
  checks: {
    database: "ok" | "error";
    cache: "ok" | "error" | "not_configured";
    aiFabric: "ok" | "error" | "not_configured";
    queues: "ok" | "error" | "not_configured";
  };
  timestamp: string;
}

// ═══════════════════════════════════════════════════════════════════════════════
// API Path Types (Contract Layer)
// ═══════════════════════════════════════════════════════════════════════════════

/** Maps API paths to their response types for contract testing */
export interface APIContractMap {
  "/api/health": { GET: HealthCheckDTO };
  "/api/startup-check": { GET: { ok: boolean; fatal: string[]; warnings: string[]; env: Record<string, boolean> } };
  "/api/auth/login": { POST: AuthResult };
  "/api/auth/refresh": { POST: AuthResult };
  "/api/auth/logout": { POST: { ok: boolean } };
  "/api/accounting/journal-entries": { GET: PaginatedResponse<VoucherDTO>; POST: VoucherDTO };
  "/api/accounting/fiscal-periods": { GET: PaginatedResponse<FinancialPeriodDTO>; POST: FinancialPeriodDTO };
  "/api/accounting/balance-sheet": { GET: Record<string, unknown> };
  "/api/accounting/profit-loss": { GET: Record<string, unknown> };
  "/api/invoices": { GET: PaginatedResponse<InvoiceDTO>; POST: InvoiceDTO };
  "/api/companies": { GET: PaginatedResponse<CompanyDTO>; POST: CompanyDTO };
  "/api/ai/agents": { POST: AIResponseDTO };
  "/api/audit": { GET: PaginatedResponse<AuditLogDTO> };
  "/api/webhooks/endpoints": { GET: PaginatedResponse<WebhookEndpointDTO>; POST: WebhookEndpointDTO };
}

/** Type-safe API client — validates response shapes at compile time */
export type APIResponse<Path extends keyof APIContractMap, Method extends keyof APIContractMap[Path]> =
  APIContractMap[Path][Method];
