/**
 * POST /api/setup/save-integrations
 * Body: {
 *   integrations: {
 *     OPENROUTER_API_KEY?: string,
 *     STRIPE_SECRET_KEY?: string,
 *     STRIPE_WEBHOOK_SECRET?: string,
 *     WHATSAPP_BUSINESS_NUMBER?: string,
 *     WHATSAPP_ACCESS_TOKEN?: string,
 *     PAYMENTS_ENC_KEY?: string,        // 32+ char encryption key
 *     NEXTAUTH_SECRET?: string,         // JWT signing secret
 *     REDIS_URL?: string,               // Valkey/Redis for BullMQ
 *     SMTP_URL?: string,                // email
 *   }
 * }
 *
 * Writes the provided integration env vars to .env. Empty values are
 * skipped (so the founder can leave optional integrations blank).
 *
 * For NEXTAUTH_SECRET and PAYMENTS_ENC_KEY, if not provided, a secure
 * random value is auto-generated.
 */

import { NextRequest } from "next/server";
import { randomBytes } from "node:crypto";
import {
  isSetupComplete,
  setupAlreadyCompleteResponse,
  upsertEnvKey,
} from "@/lib/setup/setup-config";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(req: NextRequest): Promise<Response> {
  if (isSetupComplete()) return setupAlreadyCompleteResponse();

  let body: { integrations?: Record<string, string> };
  try {
    body = await req.json();
  } catch {
    return Response.json({ ok: false, error: "Invalid JSON body" }, { status: 400 });
  }

  const integrations = body.integrations || {};
  const writtenKeys: string[] = [];
  const skippedKeys: string[] = [];

  // Auto-generate required secrets if not provided
  const finalValues: Record<string, string> = { ...integrations };

  if (!finalValues.NEXTAUTH_SECRET) {
    finalValues.NEXTAUTH_SECRET = randomBytes(48).toString("base64");
  }
  if (!finalValues.PAYMENTS_ENC_KEY) {
    // 32-character hex string (AES-256 key)
    finalValues.PAYMENTS_ENC_KEY = randomBytes(16).toString("hex");
  }

  // Allowed integration keys (whitelist — no arbitrary env injection)
  const ALLOWED_KEYS = new Set([
    "OPENROUTER_API_KEY",
    "STRIPE_SECRET_KEY",
    "STRIPE_WEBHOOK_SECRET",
    "WHATSAPP_BUSINESS_NUMBER",
    "WHATSAPP_ACCESS_TOKEN",
    "PAYMENTS_ENC_KEY",
    "NEXTAUTH_SECRET",
    "REDIS_URL",
    "SMTP_URL",
    "TWILIO_ACCOUNT_SID",
    "TWILIO_AUTH_TOKEN",
    "ZATCA_API_BASE_URL",
    "SENTRY_DSN",
  ]);

  for (const [key, value] of Object.entries(finalValues)) {
    if (!ALLOWED_KEYS.has(key)) {
      skippedKeys.push(key);
      continue;
    }
    if (typeof value !== "string" || value.trim() === "") {
      skippedKeys.push(key);
      continue;
    }
    try {
      upsertEnvKey(key, value.trim());
      writtenKeys.push(key);
    } catch (err) {
      return Response.json(
        { ok: false, error: `Failed to write ${key} to .env: ${(err as Error).message}` },
        { status: 500 },
      );
    }
  }

  return Response.json({
    ok: true,
    written: writtenKeys,
    skipped: skippedKeys,
    autogenerated: !integrations.NEXTAUTH_SECRET ? ["NEXTAUTH_SECRET"] : [],
  });
}
